# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
type: Opaque
data:
  # arbitrary desired key, value pairs (base64 encoded)
  # echo -n "example_user" | base64
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==

